### ISSUE TITLE
Changing to a different .4ds file (also stored to streamingAssets)

### ISSUE THREAD

**Issue by yosun** [keijiro/4DViewsTest2#1]
Also trying out .4ds ... do you know how to switch to play a different .4ds file at runtime? 

Have tried the obvious .Stop() assign squencename and .Play() and now trying a coroutine to wait for initialization... But I have not been able to get the Unity plugin to change the play file at runtime. 

`public void SelectThis(string name)
    {
        if (p4ds.IsPlaying) p4ds.Stop();
        print("SelectThis " + name);

        p4ds.SequenceName = name+".4ds";
        p4ds.Initialize(true);

        p4ds.Play(true);

        StartCoroutine(WaitToPlay());
    }

    IEnumerator WaitToPlay()
    {
        while (!p4ds.IsInitialized)
            yield return new WaitForSeconds(0.1f);

    //    p4ds.Play(false);
        p4ds.Play(true);
        print("PLAYING!!!! SelectThis " + p4ds.SequenceName);
    }`

**Comment by keijiro** [comment]
This repository is not relevant to the 4ds format. Please make sure that you're referring to the correct repository.
