### ISSUE TITLE
Basic rig missing prefab?

### ISSUE THREAD

**Issue by skymeson** [keijiro/4DViewsTest2#2]
It's possible something got messed up updating to 2019.4.4f1 but I'm not seeing anything when I run the scenes. It may have to do with a missing prefab. 

Sample4DViews_SwordFighting_60fps_FILTERED (Missing Prefab)

![adfadfgadf](https://user-images.githubusercontent.com/2335758/88026257-972ef980-cb03-11ea-830d-a3f7608dfffd.PNG)

I was getting another strange error initially when I started the project from scratch. 
"The type or namespace name 'Event' could not be found"

I was able to fix this by Resetting packages to Default and then reloading packages through package manifest, but this may be confusing to others.

**Comment by keijiro** [comment]
Have you downloaded and imported the volumetric video file? From README.md:

> The volumetric video data files are missing from this repository. You can download them from the Resources page of the 4DViews site.

Regarding the error message, it's a compatibility issue between 2019.4.3 and 2019.4.4. It's recommended to use 2019.4.3.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen it.

**Comment by skymeson** [comment]
Feel free to close issue. I switched to 2019.4.3 and put 4DViews assets in correct locations. Project opens up just fine. Thank you!

**Comment by dh7300** [comment]
I read the README.md and received the resource, but I have no idea what to do after that. Can you explain a little bit more about HAP site and ffmpeg.sh? I really want to know about this project.
When I download this project, I am curious about how to solve the Missing Prefab.
