### ISSUE TITLE
Missing Prefab

### ISSUE THREAD

**Issue by dh7300** [keijiro/4DViewsTest2#3]
<img width="994" alt="4ds" src="https://user-images.githubusercontent.com/69621922/93425615-5251f400-f8f5-11ea-828b-531093c20c6d.png">

I read the README.md and received the resource, but I have no idea what to do after that. Can you explain a little bit more about HAP site and ffmpeg.sh? I really want to know about this project.
When I download this project, I am curious about how to solve the Missing Prefab. Please.

**Comment by keijiro** [comment]
- Install ffmpeg on a Linux system.
- Execute ffmpeg.sh to convert texture files into a .mov file.
- put the .mov file in the StreamingAsset directory.
