### ISSUE TITLE
Modeling does not move.

### ISSUE THREAD

**Issue by dh7300** [keijiro/4DViewsTest2#4]
<img width="805" alt="4d1" src="https://user-images.githubusercontent.com/69621922/93727642-035ad600-fbf7-11ea-9c55-d71b0c092cc8.png">

<img width="1228" alt="4d2" src="https://user-images.githubusercontent.com/69621922/93727646-048c0300-fbf7-11ea-8fdb-6f3418abd94b.png">

<img width="1232" alt="4d3" src="https://user-images.githubusercontent.com/69621922/93727647-05249980-fbf7-11ea-9b99-1438ba93745c.png">

<img width="1224" alt="4d4" src="https://user-images.githubusercontent.com/69621922/93727649-05bd3000-fbf7-11ea-945d-04abb9a29186.png">

<img width="721" alt="4d5" src="https://user-images.githubusercontent.com/69621922/93727730-6e0c1180-fbf7-11ea-9b24-4f9b3f99fab0.png">

I even succeeded in creating a .mov file with hap using ffmpeg with textures. However, I put the .mov file in the streaming assets folder, but when I click play, the models do not move. Can you see the screenshot and report the problem?

**Comment by keijiro** [comment]
Are you using the correct version of Unity? (2019.4.1f1)

**Comment by dh7300** [comment]
Yes I am using the (2019.4.1f1) version.

**Comment by keijiro** [comment]
How about trying the Preview scene? (Assets/Preview.unity)
It's the simplest example, so it should run on every computer.

**Comment by dh7300** [comment]
<img width="1751" alt="4d6" src="https://user-images.githubusercontent.com/69621922/93733198-69535780-fc0f-11ea-9eb6-90abc57ae9a6.png">


Maybe this is the problem? When I hit play, I get a button called Recreate Missing Nodes in the Alembic Stream Player script.
Is there a workaround for this?

**Comment by keijiro** [comment]
It seems like something is broken. I'd recommend starting over from cloning the repository.

**Comment by dh7300** [comment]
We started cloning the repository again, but this time in the Alembic Stream Player script.
You will see a button called Recreate Missing Nodes.
Is it correct to replace the first missing prefab part with the .abc file obtained from the resource site?

**Comment by keijiro** [comment]
> Is it correct to replace the first missing prefab part with the .abc file obtained from the resource site?

No. It can't be simple replaced.

You should put the .abc file (obtained from the 4DViews site) in `Assets/Alembic` before opening the project first time. Then it should work correctly.

**Comment by keijiro** [comment]
I started over from cloning the project and confirmed that it works correctly.

**Comment by dh7300** [comment]
OMG.. Thank you.
Please be sure to include this information in the README.

And how do I apply the .abc file and .mov file that I have created, not the file received from the resource site?

**Comment by keijiro** [comment]
The timelines, camera movements and visual effects are designed for the Sword Fighting clip. They wouldn't work with other clips.

**Comment by keijiro** [comment]
I'm closing this issue as resolved. Please feel free to reopen it if it still reproduces.
